package deploy

import (
	"bytes"
	"fmt"
	"text/template"
)

const envTemplate = `# Netsoft ZTNA - NetBird Stack Environment
# Generated by wizard - DO NOT EDIT MANUALLY
NETBIRD_DOMAIN={{.Domain}}
DATABASE_PASSWORD={{.DatabasePassword}}
SSL_CERT_PATH={{.SSLCertPath}}
SSL_KEY_PATH={{.SSLKeyPath}}
OIDC_ENABLED={{.OIDCEnabled}}
OIDC_ISSUER={{.OIDCIssuer}}
OIDC_CLIENT_ID={{.OIDCClientID}}
OIDC_CLIENT_SECRET={{.OIDCClientSecret}}
AUTH_AUTHORITY={{.AuthAuthority}}
`

func GenerateEnv(data *ComposeData) (string, error) {
	tmpl, err := template.New("env").Parse(envTemplate)
	if err != nil {
		return "", fmt.Errorf("parse env template: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("execute env template: %w", err)
	}
	return buf.String(), nil
}
